### ISSUE TITLE
run.sh entrypoint script missing

### ISSUE THREAD

**Issue by knight-of-ni** [leosac/leosac-web#1]
Dockerfile tries to add `run.sh` as the entrypoint, but that file does not exist in the project:
https://github.com/leosac/leosac-web/blob/master/Dockerfile#L20

**Comment by Maxhy** [comment]
Oh indeed, thanks for trying.
I added the missing file.

**Comment by knight-of-ni** [comment]
Boom! `cd /leosac-web/app` was what I was missing. Thank you.
